name: MeroShare Script

on:
  schedule:
    - cron: "0 9 * * 1,4"   # Runs 09:00 UTC on Monday & Thursday
  workflow_dispatch:        # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Debug env
        run: |
          echo "CLIENT_ID length: ${#MEROSHARE_CLIENT_ID}"
          echo "USERNAME length: ${#MEROSHARE_USERNAME}"
        env:
          MEROSHARE_CLIENT_ID: ${{ secrets.MEROSHARE_CLIENT_ID }}
          MEROSHARE_USERNAME: ${{ secrets.MEROSHARE_USERNAME }}
          
      - name: Run script
        run: node app.js
        env:
          MEROSHARE_CLIENT_ID: ${{ secrets.MEROSHARE_CLIENT_ID }}
          MEROSHARE_USERNAME: ${{ secrets.MEROSHARE_USERNAME }}
          MEROSHARE_PASSWORD: ${{ secrets.MEROSHARE_PASSWORD }}
          EMAIL1: ${{ secrets.EMAIL1 }}
          EMAIL2: ${{ secrets.EMAIL2 }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}  
          MEROSHARE_API: ${{ secrets.MEROSHARE_API }}
            
